title: Guía CCPEMS
description: >- # this means to ignore newlines until "baseurl:"
  A Bootstrap 4 start up project for Jekyll and Github Pages
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#github_username:  NatiSkr

repository: "NatiSkr/ccpems-unofficial"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# A list of the pages to display in the navigation bar
header_pages:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
